.\"
.\" $Id: lssum.1,v 1.2 2018/10/25 05:33:18 urs Exp $
.\"
.TH LSSUM 1 "Oct 25, 2018" "" "User Commands"
.SH NAME
lssum \- list files with their MD5 hash
.SH SYNOPSIS
.B lssum
.RB [ \-c ]
.IR file " ..."
.SH DESCRIPTION
.B lssum
lists the named files along with their size, modification time, and
MD5 hash.
.SH OPTIONS
.TP
.B \-c
Show last status change time in addition to modification time.
.TP
.B \-u
Add user name to output.
.TP
.B \-g
Add group name to output.
.SH "SEE ALSO"
.BR ls "(1), " md5sum (1)
.SH AUTHOR
Urs Thuermann <urs@isnogud.escape.de>
